using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EventBinderGenerator
{
    [Generator]
    public class EventBinderSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 특별한 초기화가 필요하지 않음
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Assembly-CSharp 어셈블리 컴파일 시에만 생성되도록 필터링
            if (context.Compilation.AssemblyName != "Assembly-CSharp")
                return;

            // 1. 모든 인터페이스 수집
            List<INamedTypeSymbol> interfaces = new List<INamedTypeSymbol>();
            CollectInterfaces(context.Compilation.GlobalNamespace, interfaces);

            List<string> characterEvents = new List<string>();
            List<string> playerEvents = new List<string>();

            // 2. 각 인터페이스 분류 (ICharacterEvent, IPlayerEvent 상속 기준)
            foreach (var iface in interfaces)
            {
                // 자기 자신 인터페이스는 제외
                if (iface.Name == "ICharacterEvent" || iface.Name == "IPlayerEvent")
                    continue;

                if (InheritsFrom(iface, "ICharacterEvent"))
                {
                    characterEvents.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
                else if (InheritsFrom(iface, "IPlayerEvent"))
                {
                    playerEvents.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }

            // 가나다 및 알파벳 순으로 정렬하여 일관된 코드 생성 보장
            characterEvents.Sort();
            playerEvents.Sort();

            // 3. 소스 코드 자동 작성
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using XLua;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("");
            sb.AppendLine("public static partial class LuaEventBinder");
            sb.AppendLine("{");

            // Character Events Binding Method
            sb.AppendLine("    public static partial void BindCharacterEvents(LuaTable luaTable, EventBus<ICharacterEvent> eventBus, List<object> activeProxies)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (luaTable == null || eventBus == null) return;");
            sb.AppendLine("");
            foreach (var evt in characterEvents)
            {
                sb.AppendLine($"        BindCharacter<{evt}>(luaTable, eventBus, activeProxies);");
            }
            sb.AppendLine("    }");
            sb.AppendLine("");

            // Character Events Unbinding Method
            sb.AppendLine("    public static partial void UnbindCharacterEvents(EventBus<ICharacterEvent> eventBus, List<object> activeProxies)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (eventBus == null || activeProxies == null) return;");
            sb.AppendLine("        foreach (var proxy in activeProxies)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (proxy == null) continue;");
            foreach (var evt in characterEvents)
            {
                string safeVar = evt.Replace(".", "_").Replace(":", "_").Replace(" ", "_").Replace("<", "_").Replace(">", "_");
                sb.AppendLine($"            if (proxy is {evt} p_{safeVar}) eventBus.Remove<{evt}>(p_{safeVar});");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("");

            // Player Events Binding Method
            sb.AppendLine("    public static partial void BindPlayerEvents(LuaTable luaTable, EventBus<IPlayerEvent> eventBus, List<object> activeProxies)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (luaTable == null || eventBus == null) return;");
            sb.AppendLine("");
            foreach (var evt in playerEvents)
            {
                sb.AppendLine($"        BindPlayer<{evt}>(luaTable, eventBus, activeProxies);");
            }
            sb.AppendLine("    }");
            sb.AppendLine("");

            // Player Events Unbinding Method
            sb.AppendLine("    public static partial void UnbindPlayerEvents(EventBus<IPlayerEvent> eventBus, List<object> activeProxies)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (eventBus == null || activeProxies == null) return;");
            sb.AppendLine("        foreach (var proxy in activeProxies)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (proxy == null) continue;");
            foreach (var evt in playerEvents)
            {
                string safeVar = evt.Replace(".", "_").Replace(":", "_").Replace(" ", "_").Replace("<", "_").Replace(">", "_");
                sb.AppendLine($"            if (proxy is {evt} p_{safeVar}) eventBus.Remove<{evt}>(p_{safeVar});");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            // 4. 소스 파일 등록
            context.AddSource("LuaEventBinder.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void CollectInterfaces(INamespaceSymbol ns, List<INamedTypeSymbol> result)
        {
            if (ns == null) return;

            foreach (var member in ns.GetMembers())
            {
                if (member is INamespaceSymbol nestedNs)
                {
                    CollectInterfaces(nestedNs, result);
                }
                else if (member is INamedTypeSymbol typeSymbol)
                {
                    CollectTypes(typeSymbol, result);
                }
            }
        }

        private void CollectTypes(INamedTypeSymbol type, List<INamedTypeSymbol> result)
        {
            if (type == null) return;

            if (type.TypeKind == TypeKind.Interface)
            {
                result.Add(type);
            }

            foreach (var nestedType in type.GetTypeMembers())
            {
                CollectTypes(nestedType, result);
            }
        }

        private bool InheritsFrom(INamedTypeSymbol symbol, string targetName)
        {
            if (symbol == null) return false;

            if (symbol.Name == targetName)
                return true;

            foreach (var iface in symbol.AllInterfaces)
            {
                if (iface.Name == targetName)
                    return true;
            }

            return false;
        }
    }
}
